---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-anythingllm
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nutanix-volume
  resources:
    requests:
      storage: 10Gi

---
kind: Service
apiVersion: v1
metadata:
  name: anythingllm
  namespace: ai
  annotations:
    metallb.universe.tf/allow-shared-ip: "123456"
spec:
  ports:
    - name: anythingllm
      port: 3001
      targetPort: anythingllm
  type: LoadBalancer
  selector:
    app: anythingllm

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ai
  name: anythingllm
  labels:
    app: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythingllm
  template:
    metadata:
      labels:
        app: anythingllm
    spec:
      volumes:
        - name: volume-anythingllm
          persistentVolumeClaim:
            claimName: pvc-anythingllm
      
      initContainers:
      - name: init-create-subdir
        image: busybox
        command: ["sh", "-c", "mkdir -p /app/server/storage && touch /app/server/storage/.env && chown -R 1000:1000 /app/server/storage && ls -al /app/server/storage"]
        volumeMounts:
          - name: volume-anythingllm
            mountPath: /app/server/storage

      containers:
      - name: anythingllm
        image: mintplexlabs/anythingllm
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: false
        volumeMounts:
         - name: volume-anythingllm
           mountPath: /app/server/.env
           subPath: .env
         - name: volume-anythingllm
           mountPath: /app/server/storage
        ports:
          - name: anythingllm
            containerPort: 3001
        env:
          - name: STORAGE_DIR
            value: /app/server/storage
          - name: TZ
            value: Europe/Zurich
